theme: jekyll-theme-minimal
title: Monty Morris: Sound Engineer
description: I've mixed sound for musicals, bands, and shows, and recorded orchestras, choirs, and rock bands. Currently, I am an in-house technician at a 500-seat theatre.
